import { execFile } from "node:child_process"
import { constants } from "node:fs"
import { access, mkdir, readFile, unlink, writeFile } from "node:fs/promises"
import { homedir } from "node:os"
import { dirname, isAbsolute, join } from "node:path"
import { promisify } from "node:util"

const execFileAsync = promisify(execFile)
const marker = "Generated by school-agent auto-prep scheduler"

export type SchedulerPlatform = "darwin" | "linux"
export type SchedulerOptions = {
  platform: SchedulerPlatform
  nodePath: string
  scriptPath: string
  configPath: string
  label: string
  homeDir?: string
  uid?: number
}
export type SchedulerCommand = { executable: string; args: string[] }
export type SchedulerFile = { path: string; content: string }
export type SchedulerPlan = {
  platform: SchedulerPlatform
  label: string
  files: SchedulerFile[]
  activate: SchedulerCommand[]
  deactivate: SchedulerCommand[]
  status: SchedulerCommand[]
}
export type CommandRunner = (command: SchedulerCommand) => Promise<{ exitCode: number }>
export type SchedulerActionResult = { applied: boolean; plan: SchedulerPlan }
export type SchedulerStatus = {
  installed: boolean
  active: boolean
  files: Array<{ path: string; exists: boolean }>
}

function absolutePath(value: string, name: string): string {
  if (!isAbsolute(value) || /[\0\r\n]/.test(value)) {
    throw new Error(`${name} must be an absolute path without control line breaks`)
  }
  return value
}

function xml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;")
}

function systemdArg(value: string): string {
  return `"${value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\$/g, () => "$$")
    .replace(/%/g, "%%")}"`
}

function assertOptions(options: SchedulerOptions): Required<SchedulerOptions> {
  const homeDir = absolutePath(options.homeDir ?? homedir(), "homeDir")
  if (!/^[A-Za-z][A-Za-z0-9_.-]*$/.test(options.label) || options.label.includes("..")) {
    throw new Error("label must be a simple service identifier")
  }
  const uid = options.uid ?? process.getuid?.()
  if (
    options.platform === "darwin" &&
    (!Number.isSafeInteger(uid) || uid === undefined || uid < 0)
  ) {
    throw new Error("macOS scheduler requires a numeric uid")
  }
  return {
    ...options,
    homeDir,
    uid: uid ?? 0,
    nodePath: absolutePath(options.nodePath, "nodePath"),
    scriptPath: absolutePath(options.scriptPath, "scriptPath"),
    configPath: absolutePath(options.configPath, "configPath"),
  }
}

/** A fixed hourly trigger. The CLI decides which enrolled class is due for prep. */
export function planAutoPrepSchedule(input: SchedulerOptions): SchedulerPlan {
  const options = assertOptions(input)
  const args = [
    options.nodePath,
    options.scriptPath,
    "--config",
    options.configPath,
    "auto-prep",
    "run",
    "--execute",
  ]
  if (options.platform === "darwin") {
    const path = join(options.homeDir, "Library", "LaunchAgents", `${options.label}.plist`)
    const content = [
      '<?xml version="1.0" encoding="UTF-8"?>',
      '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
      '<plist version="1.0">',
      `<dict><!-- ${marker} -->`,
      `<key>Label</key><string>${xml(options.label)}</string>`,
      "<key>ProgramArguments</key><array>",
      ...args.map((arg) => `<string>${xml(arg)}</string>`),
      "</array>",
      "<key>StartCalendarInterval</key><dict><key>Minute</key><integer>0</integer></dict>",
      "</dict></plist>",
      "",
    ].join("\n")
    const domain = `gui/${options.uid}`
    return {
      platform: options.platform,
      label: options.label,
      files: [{ path, content }],
      activate: [{ executable: "launchctl", args: ["bootstrap", domain, path] }],
      deactivate: [{ executable: "launchctl", args: ["bootout", `${domain}/${options.label}`] }],
      status: [{ executable: "launchctl", args: ["print", `${domain}/${options.label}`] }],
    }
  }

  const base = join(options.homeDir, ".config", "systemd", "user", options.label)
  const service = [
    `# ${marker}`,
    "[Unit]",
    "Description=School Agent automatic class prep",
    "[Service]",
    "Type=oneshot",
    `ExecStart=${args.map(systemdArg).join(" ")}`,
    "",
  ].join("\n")
  const timer = [
    `# ${marker}`,
    "[Unit]",
    "Description=Run School Agent automatic class prep hourly",
    "[Timer]",
    "OnCalendar=hourly",
    "Persistent=true",
    "[Install]",
    "WantedBy=timers.target",
    "",
  ].join("\n")
  const timerName = `${options.label}.timer`
  return {
    platform: options.platform,
    label: options.label,
    files: [
      { path: `${base}.service`, content: service },
      { path: `${base}.timer`, content: timer },
    ],
    activate: [
      { executable: "systemctl", args: ["--user", "daemon-reload"] },
      { executable: "systemctl", args: ["--user", "enable", "--now", timerName] },
    ],
    deactivate: [
      { executable: "systemctl", args: ["--user", "disable", "--now", timerName] },
      { executable: "systemctl", args: ["--user", "daemon-reload"] },
    ],
    status: [{ executable: "systemctl", args: ["--user", "is-active", "--quiet", timerName] }],
  }
}

export async function defaultCommandRunner(
  command: SchedulerCommand,
): Promise<{ exitCode: number }> {
  try {
    await execFileAsync(command.executable, command.args)
    return { exitCode: 0 }
  } catch (error) {
    const exitCode = (error as NodeJS.ErrnoException & { code?: number }).code
    if (typeof exitCode === "number") return { exitCode }
    throw error
  }
}

async function exists(path: string): Promise<boolean> {
  try {
    await access(path, constants.F_OK)
    return true
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return false
    throw error
  }
}

function assertHost(platform: SchedulerPlatform): void {
  if (process.platform !== platform)
    throw new Error(`Cannot apply ${platform} scheduler on ${process.platform}`)
}

function statusCommand(plan: SchedulerPlan): SchedulerCommand {
  const command = plan.status[0]
  if (!command) throw new Error("Scheduler plan is missing a status command")
  return command
}

async function runAll(commands: SchedulerCommand[], run: CommandRunner): Promise<void> {
  for (const command of commands) {
    const result = await run(command)
    if (result.exitCode !== 0)
      throw new Error(`${command.executable} ${command.args[0]} failed (${result.exitCode})`)
  }
}

export async function installAutoPrepSchedule(
  options: SchedulerOptions,
  control: { apply?: boolean; run?: CommandRunner } = {},
): Promise<SchedulerActionResult> {
  const plan = planAutoPrepSchedule(options)
  if (!control.apply) return { applied: false, plan }
  assertHost(plan.platform)
  const existing = await Promise.all(
    plan.files.map(async (file) => ({ ...file, exists: await exists(file.path) })),
  )
  for (const file of existing) {
    if (file.exists && !(await readFile(file.path, "utf8")).includes(marker)) {
      throw new Error(`Refusing to replace unmanaged scheduler file: ${file.path}`)
    }
  }
  const run = control.run ?? defaultCommandRunner
  if (existing.some((file) => file.exists)) {
    if (plan.platform === "linux") {
      await runAll(plan.deactivate.slice(0, 1), run)
    } else {
      const active = await run(statusCommand(plan))
      if (active.exitCode === 0) await runAll(plan.deactivate.slice(0, 1), run)
    }
  }
  for (const file of plan.files) {
    await mkdir(dirname(file.path), { recursive: true })
    await writeFile(file.path, file.content, { mode: 0o600 })
  }
  await runAll(plan.activate, run)
  return { applied: true, plan }
}

export async function uninstallAutoPrepSchedule(
  options: SchedulerOptions,
  control: { apply?: boolean; run?: CommandRunner } = {},
): Promise<SchedulerActionResult> {
  const plan = planAutoPrepSchedule(options)
  if (!control.apply) return { applied: false, plan }
  assertHost(plan.platform)
  const owned: string[] = []
  for (const file of plan.files) {
    if (!(await exists(file.path))) continue
    if (!(await readFile(file.path, "utf8")).includes(marker)) {
      throw new Error(`Refusing to remove unmanaged scheduler file: ${file.path}`)
    }
    owned.push(file.path)
  }
  if (owned.length === 0) return { applied: true, plan }
  const run = control.run ?? defaultCommandRunner
  if (plan.platform === "linux") {
    await runAll(plan.deactivate.slice(0, 1), run)
  } else {
    const active = await run(statusCommand(plan))
    if (active.exitCode === 0) await runAll(plan.deactivate.slice(0, 1), run)
  }
  for (const path of owned) await unlink(path)
  if (plan.platform === "linux") await runAll(plan.deactivate.slice(1), run)
  return { applied: true, plan }
}

/** Read-only, including the service manager query. */
export async function getAutoPrepScheduleStatus(
  options: SchedulerOptions,
  run: CommandRunner = defaultCommandRunner,
): Promise<SchedulerStatus> {
  const plan = planAutoPrepSchedule(options)
  const files = await Promise.all(
    plan.files.map(async (file) => ({ path: file.path, exists: await exists(file.path) })),
  )
  const active = (await run(statusCommand(plan))).exitCode === 0
  return { installed: files.every((file) => file.exists), active, files }
}
